#
# Package (build and test) application
#
name: Package application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install npm packages
        shell: bash
        run: npm install
      - name: Run lint commands
        shell: bash
        run: npm run lint
      - name: Run prettier commands
        shell: bash
        run: npm run prettier
      - name: Run build commands
        shell: bash
        run: npm run build
      - name: Run test commands
        shell: bash
        run: npm run test
