#
# Publish artifacts
#
name: Publish Artifacts

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/app:latest .
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/app:latest
      - name: Make GHCR image public
        run: |
          curl -X PUT https://api.github.com/orgs/h5radar/packages/container/app/visibility \
            -H "Authorization: Bearer ${{ secrets.GHCR_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            -d '{"visibility":"public"}'
